# Generated by Django 3.1.4 on 2021-01-10 06:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom_link', models.URLField(verbose_name='Zoom Link')),
                ('score', models.IntegerField(verbose_name='Team Score')),
                ('users', models.ManyToManyField(related_name='team_members', to=settings.AUTH_USER_MODEL, verbose_name='Team Players')),
            ],
        ),
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teams', models.ManyToManyField(related_name='game_room', to='game_room.Team', verbose_name='Teams')),
            ],
        ),
    ]
