# Generated by Django 3.1.4 on 2021-01-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='zoom_link',
        ),
        migrations.AddField(
            model_name='team',
            name='access_token1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='accesstoken'),
        ),
        migrations.AddField(
            model_name='team',
            name='access_token2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='accestoken'),
        ),
        migrations.AddField(
            model_name='team',
            name='room_sid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Room Sid'),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='teams',
            field=models.ManyToManyField(blank=True, null=True, related_name='game_room', to='game_room.Team', verbose_name='Teams'),
        ),
        migrations.AlterField(
            model_name='team',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Team Score'),
        ),
    ]
