# Generated by Django 3.1.4 on 2021-01-10 15:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_room', '0002_auto_20210110_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='access_token1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='accesstoken 1'),
        ),
        migrations.AlterField(
            model_name='team',
            name='access_token2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='accestoken 2'),
        ),
        migrations.AlterField(
            model_name='team',
            name='users',
            field=models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='Team Players'),
        ),
        migrations.CreateModel(
            name='QueueRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.TimeField(auto_now_add=True, verbose_name='time queue started')),
                ('players_waiting', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Players Waiting to Queue')),
            ],
        ),
    ]
