# Generated by Django 3.1.4 on 2021-01-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_room', '0003_auto_20210110_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Room status'),
        ),
    ]
