# Generated by Django 3.1.4 on 2021-01-10 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('users', '0002_auto_20210110_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='default_topics',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Physics', 'Physics'), ('Pre-Calc', 'Pre-Calc')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='interest',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Football', 'Football'), ('Fencing', 'Fencing')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.school', verbose_name='school'),
        ),
    ]
