# Generated by Django 3.1.4 on 2021-01-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='School Name')),
                ('email_extension', models.CharField(max_length=50, verbose_name='Email Extension')),
            ],
        ),
    ]
